
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_SOCIALNETWORK_USERDATA_SUCCESS = 'USER_SOCIALNETWORK_USERDATA_SUCCESS';
export const SEND_CODE_TO_USER_PHONENUMBER_SUCCESS = 'SEND_CODE_TO_USER_PHONENUMBER_SUCCESS';
export const IS_USER_VERIFIED_SUCCESS = 'IS_USER_VERIFIED_SUCCESS';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const LOADING_ADDRESSES_SUCCESS = 'LOADING_ADDRESSES_SUCCESS';
export const USER_UPDATE_PROFILE_INFO_SUCCESS = 'USER_UPDATE_PROFILE_INFO_SUCCESS';
export const USER_ADD_ADDRESS_SUCCESS = 'USER_ADD_ADDRESS_SUCCESS';
export const USER_EMAIL_AND_PASSWORD_SUCCESS = 'USER_EMAIL_AND_PASSWORD_SUCCESS';
//MENU_MODAL_SUCCESS
export const MENU_MODAL_SUCCESS = "MENU_MODAL_SUCCESS";
