
const LOGO = require('../../../assets/images/logo.png');

const screen = {
    SCREEN_TITLE_ALIGN_CENTER: "center",
    SCREEN_TITLE_MEASUREMENT: "Measurement",
    SCREEN_TITLE_LOGIN: "Login",
    SCREEN_TITLE_HOME: "Home",
    SCREEN_TITLE_ITEM: "Add Item",
    SCREEN_TITLE_CALENDAR: "Calendar",
    SCREEN_TITLE_PROGRAM: "Programs",
    SCREEN_TITLE_PROGRAM_LIBRARY: "Program Library",
    SCREEN_TITLE_START_SESSION: "Start Session",
    SCREEN_TITLE_WORK_TEMPLATE: "Work Template",
    SCREEN_TITLE_WORKOUT: "Workouts",
    SCREEN_TITLE_WORKOUT_LIBRARY: "Work Library",
    SCREEN_TITLE_NUTRITION: "Nutrition",
    SCREEN_TITLE_CUSTOM: "Custom",
    SCREEN_TITLE_SHOPPINGLIST: "Shopping List",
    SCREEN_TITLE_MARKETPLACE: "Marketplace",
    SCREEN_TITLE_PACKAGE: "Packages",
    SCREEN_TITLE_CREDIT: "Credit Packages",
    SCREEN_TITLE_NOTIFICAONS: "Notifications",
    SCREEN_TITLE_ACCOUNT_DETAILS: "Account Details",
    SCREEN_TITLE_INTEGRATION: "Integrations",
    SCREEN_TITLE_UNIT_MEASUREMENT: "Unit of Measurement",
    SCREEN_TITLE_MEDIA: "Media",
    SCREEN_TITLE_SETTING: "Settings",
    SCREEN_TITLE_UPLOAD_PHOTO: "Upload Photo",
    SCREEN_TITLE_PROGRESS_PHOTO: "Progress Photo",
    SCREEN_TITLE_CURRENT_WORKOUT: "Current Workout",
    SCREEN_TITLE_CHAT: "Chats",
    SCREEN_TITLE_NUTRITION_LIBRARY: "Nutrition Library",
    reset_password_label: "Please enter your email address below to reset your password",
    unitMeasurement_Serving_Size:"Serving Size",
    unitMeasurement_Colories:"Colories",
    unitMeasurement_Protein:"Protein (g)",  
    unitMeasurement_Carbohydrates:"Total Carbohydrates (g)",
    unitMeasurement_Sugars:"Sugars (g)",
    unitMeasurement_Fat:"Total Fat (g)",
    unitMeasurement_SaturatedFat:"Saturated Fat (g)",
    unitMeasurement_Polyunsaturated:"Polyunsaturated (g)",
    unitMeasurement_Monounsaturated:"Monounsaturated (g)",
    unitMeasurement_Cholestrol:"Cholestrol (mg)",
    unitMeasurement_Sodium:"Sodium (mg)",
    unitMeasurement_Potassium:"Potassium (mg)",
    unitMeasurement_DietaryFiber:"Dietary Fiber (g)",
    unitMeasurement_VitaminA:"Vitamin A (%)",
    unitMeasurement_VitaminC:"Vitamin C (%)",
    unitMeasurement_Calcium:"Calcium (%)",
    unitMeasurement_Iron:"Iron (%)",
};

const route = {
    EXERCISE: "Exercise",
    AuthLoading:"AuthLoading",
    PROGRAM_DETAIL: "ProgramDetail",
    WEEK_DETAIL: "WeekDetail",
    MEASUREMENT: "Measurement",
    LOGIN: "Login",
    HOME: "Home",
    ITEM: "AddItem",
    NUTRITIONITEM: "AddNutritionItem",
    FILE: "Files",
    CHATSETTING: "ChatSettings",
    FORM: "Forms",
    CHAT: "Chat",
    FINANCIAL: "Financials",
    UNIT_MEASUREMENT: "UnitMeasurement",
    HUB: "Hub",
    CALENDAR: "Calendar",
    PROGRAM: "Programs",
    SETTING: "Settings",
    CHATSCREEN: "ChatScreen",
    PROGRAM_LIBRARY: "ProgramLibrary",
    START_SESSION: "StartWorkout",
    WORK_TEMPLATE: "WorkoutTemplate",
    UPDATE_NOTIFICATIONS: "UpdateNotificationSettings",
    INTEGRATION: "Integrations",
    WORKOUT: "Workouts",
    WORKOUTHISTORY: "WorkoutHistory",
    WORKOUT_LIBRARY: "WorkoutLibrary",
    NUTRITION_LIBRARY: "NutritionLibrary",
    NUTRITION: "Nutrition",
    MARKETPLACE: "Marketplace",
    PACKAGE: "Packages",
    CREDIT: "CreditPackages",
    NOTIFICAONS: "Notifications",
    ACCOUNT_DETAILS: "MyDetails",
    MEDIA: "Media",
    UPLOAD_PHOTO: "UploadPhoto",
    LOG_NUTRITION: "LogNutrition",
    WORKOUT_DETAIL: "WorkoutDetails",
    PROGRESS_PHOTO: "ProgressPhoto",
    CURRENT_WORKOUT: "CurrentWorkout",
    PROGRAM_CURRENT_WORKOUT: "ProgramCurrentWorkout",
    NUTRITION_DETAIL: "Nutrition Detail"

}
const TOKEN = "token";
const MULTIPART = "multipart";
const EMPTY = "";
const ICON_COLOR = "lightgray";
const SUCCESS_CODE = '000'

export {
    screen,
    route,
    TOKEN,
    EMPTY,
    MULTIPART,
    LOGO,
    ICON_COLOR,
    SUCCESS_CODE
}